from django.contrib import admin
from .import models as m

admin.site.register(m.CharName)
admin.site.register(m.CompanyName)
admin.site.register(m.CompanyType)
admin.site.register(m.CastInfo)
admin.site.register(m.CompCastType)
admin.site.register(m.CompleteCast)
admin.site.register(m.InfoType)
admin.site.register(m.LinkType)
admin.site.register(m.Keyword)
admin.site.register(m.MovieKeyword)
admin.site.register(m.MovieInfoIdx)
admin.site.register(m.MovieCompanies)
admin.site.register(m.PersonInfo)
admin.site.register(m.Title)
admin.site.register(m.KindType)
admin.site.register(m.AkaName)
admin.site.register(m.Name)
admin.site.register(m.AkaTitle)
admin.site.register(m.RoleType)
admin.site.register(m.MovieLink)
admin.site.register(m.MovieInfo)
